services:
  # Frontend React application
  - type: web
    name: resource-pulse
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://resource-pulse-backend.onrender.com/api
  
  # Backend Node.js service
  - type: web
    name: resource-pulse-backend
    env: node
    buildCommand: cd resource-pulse-backend && npm install
    startCommand: cd resource-pulse-backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /api