services:
  - type: web
    name: resource-pulse
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: npm install && npm run build
    # No start command needed for Docker
    envVars:
      - key: NODE_VERSION
        value: 18