services:
  - type: web
    name: resource-pulse
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free # or specify your plan
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /
    # No build command needed as it's in the Dockerfile